version: 2
updates:
  - package_ecosystem: "terraform"
    directory: "/terraform"
    schedule: 
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/terraform"
    schedule:
      interval: "monthly"