name: Terraform Plan on Push to Main

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: "06db7845-49d9-4a99-b5c3-ed940162972d"
          tenant-id: "6b99c178-e515-4bb7-bda4-073a8601a463"
          subscription-id: "ed650814-527f-4ad3-98f7-9af062cc8adf"

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show